### ISSUE TITLE
Climate system shut down

### ISSUE THREAD

**Issue by MO-Katy** [formicidae-tracker/zeus#4]
Zeus recently stopped running mid-experiment with the following error message:
```
[zone/box/climate]: 2020/10/24 08:00:04 New interpolation transition from 'night' to 'day' in 2h0m0s at 2020-10-24 06:00:00 +0000 UTC
fatal error: concurrent map read and map write

goroutine 11017 [running]:
runtime.throw(0x93c549, 0x21)
/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc000160eb8 sp=0xc000160e88 pc=0x42d652
runtime.mapaccess1_faststr(0x89d280, 0xc0001432c0, 0xc0000246a0, 0x1f, 0x0)
/usr/local/go/src/runtime/map_faststr.go:21 +0x469 fp=0xc000160f28 sp=0xc000160eb8 pc=0x413989
main.(*alarmMonitor).Monitor.func3(0xc00021c7c0, 0xc0001432c0, 0xc0000246a0, 0x1f)
/usr/local/src/zeus/zeus/alarm_monitor.go:91 +0x66 fp=0xc000160fc0 sp=0xc000160f28 pc=0x832f36
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000160fc8 sp=0xc000160fc0 pc=0x459aa1
created by main.(*alarmMonitor).Monitor
/usr/local/src/zeus/zeus/alarm_monitor.go:89 +0x57b

goroutine 1 [chan receive, 728 minutes]:
main.(*RunCommand).Execute(0xd4daf8, 0xc000142660, 0x0, 0x3, 0xd4daf8, 0x1)
/usr/local/src/zeus/zeus/run.go:161 +0x1450
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc0000ba480, 0xc0000bc050, 0x3, 0x3, 0x8, 0x93f5e1, 0x27, 0x947953, 0xc0000dbf88)
/root/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:316 +0x8ce
github.com/jessevdk/go-flags.(*Parser).Parse(...)
/root/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:186
main.main()
/usr/local/src/zeus/zeus/main.go:42 +0x87

goroutine 20 [syscall, 728 minutes]:
os/signal.signal_recv(0x0)
/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 25 [syscall, 728 minutes]:
syscall.Syscall(0x0, 0x3, 0xc0001a36b8, 0x10, 0x442cec, 0x8, 0x87fa40)
/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
golang.org/x/sys/unix.read(0x3, 0xc0001a36b8, 0x10, 0x10, 0x0, 0x0, 0x0)
/root/go/pkg/mod/golang.org/x/sys@v0.0.0-20190215142949-d0b11bdaac8a/unix/zsyscall_linux_amd64.go:1178 +0x5a
golang.org/x/sys/unix.Read(...)
/root/go/pkg/mod/golang.org/x/sys@v0.0.0-20190215142949-d0b11bdaac8a/unix/syscall_unix.go:139
github.com/atuleu/golang-socketcan.(*rawInterface).Receive(0xc00021c000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/root/go/pkg/mod/github.com/atuleu/golang-socketcan@v0.2.0/raw_interface_linux.go:53 +0xca
main.(*busManager).receiveAndStampMessage(0xc00021e000, 0xc0000baae0)
/usr/local/src/zeus/zeus/bus_manager.go:47 +0x49
created by main.(*busManager).Listen
/usr/local/src/zeus/zeus/bus_manager.go:88 +0x2c0

goroutine 52 [IO wait]:
internal/poll.runtime_pollWait(0x7f8187f7ce98, 0x72, 0xffffffffffffffff)
/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000242098, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000242080, 0xc00024a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc000242080, 0xc00024a000, 0x1000, 0x1000, 0x4040ff, 0xc0000d7c38, 0xc0000d7c40)
/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000226020, 0xc00024a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
/usr/local/go/src/net/net.go:177 +0x69
bufio.(*Reader).Read(0xc0002102a0, 0xc0001fe270, 0x1, 0x9, 0x42cc71, 0x3, 0xc00003cf70)
/usr/local/go/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0x9cc480, 0xc0002102a0, 0xc0001fe270, 0x1, 0x9, 0x1, 0x0, 0x0, 0xc0000d7db0)
/usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(...)
/usr/local/go/src/io/io.go:329
encoding/gob.decodeUintReader(0x9cc480, 0xc0002102a0, 0xc0001fe270, 0x9, 0x9, 0x406e6c, 0xc0001e8480, 0xc0000d7db0, 0x42c3cf)
/usr/local/go/src/encoding/gob/decode.go:120 +0x70
encoding/gob.(*Decoder).recvMessage(0xc000242100, 0xc0000d7dc8)
/usr/local/go/src/encoding/gob/decoder.go:81 +0x57
encoding/gob.(*Decoder).decodeTypeSequence(0xc000242100, 0x94d700, 0xc000242100)
/usr/local/go/src/encoding/gob/decoder.go:143 +0x12c
encoding/gob.(*Decoder).DecodeValue(0xc000242100, 0x86f9e0, 0xc000143290, 0x16, 0x0, 0x0)
/usr/local/go/src/encoding/gob/decoder.go:211 +0xf6
encoding/gob.(*Decoder).Decode(0xc000242100, 0x86f9e0, 0xc000143290, 0x0, 0x0)
/usr/local/go/src/encoding/gob/decoder.go:188 +0x191
net/rpc.(*gobClientCodec).ReadResponseHeader(0xc000214660, 0xc000143290, 0xc000168000, 0x0)
/usr/local/go/src/net/rpc/client.go:228 +0x45
net/rpc.(*Client).input(0xc000210360)
/usr/local/go/src/net/rpc/client.go:109 +0xa2
created by net/rpc.NewClientWithCodec
/usr/local/go/src/net/rpc/client.go:206 +0x89

goroutine 53 [select]:
main.(*RPCReporter).Report(0xc000248120, 0xc0001fe070)
/usr/local/src/zeus/zeus/rpc.go:99 +0x228
created by main.(*RunCommand).Execute
/usr/local/src/zeus/zeus/run.go:108 +0xd4b

goroutine 54 [chan receive, 728 minutes]:
main.(*FileClimateReporter).Report(0xc000214c90)
/usr/local/src/zeus/zeus/climate_reporter.go:26 +0x2fb
created by main.ComputeZoneRequirements
/usr/local/src/zeus/zeus/zone.go:21 +0x992

goroutine 55 [runnable]:
main.(*alarmMonitor).Monitor(0xc00021c7c0)
/usr/local/src/zeus/zeus/alarm_monitor.go:59 +0x1c4
created by main.(*RunCommand).Execute
/usr/local/src/zeus/zeus/run.go:126 +0x925

goroutine 56 [chan receive, 2 minutes]:
main.(*RunCommand).Execute.func1(0xc000214060, 0xc0001fc020, 0xc000214030)
/usr/local/src/zeus/zeus/run.go:129 +0x1d5
created by main.(*RunCommand).Execute
/usr/local/src/zeus/zeus/run.go:128 +0x9a8

goroutine 57 [select]:
main.(*InterpolationManager).Interpolate(0xc00021a550, 0xc0001fe060, 0xc000216000, 0xc000216060)
/usr/local/src/zeus/zeus/interpolation_manager.go:103 +0x407
created by main.(*RunCommand).Execute
/usr/local/src/zeus/zeus/run.go:145 +0x362

goroutine 58 [select]:
main.(*busManager).Listen(0xc00021e000)
/usr/local/src/zeus/zeus/bus_manager.go:99 +0x41b
main.(*RunCommand).Execute.func3(0xc0001fc510, 0xc0001fe660)
/usr/local/src/zeus/zeus/run.go:152 +0x33
created by main.(*RunCommand).Execute
/usr/local/src/zeus/zeus/run.go:151 +0x1358

goroutine 11018 [runnable]:
fmt.(*pp).printValue(0xc00012e0c0, 0x87e240, 0xcf2c41, 0x88, 0x7f8100000064, 0x0)
/usr/local/go/src/fmt/print.go:709 +0x280d
fmt.(*pp).printArg(0xc00012e0c0, 0x87e240, 0xcf2c41, 0xc000000064)
/usr/local/go/src/fmt/print.go:702 +0x2ba
fmt.(*pp).doPrintf(0xc00012e0c0, 0x9382ff, 0x1a, 0xc000069eb0, 0x3, 0x3)
/usr/local/go/src/fmt/print.go:1016 +0x158
fmt.Sprintf(0x9382ff, 0x1a, 0xc0003086b0, 0x3, 0x3, 0x4, 0xc0003086b8)
/usr/local/go/src/fmt/print.go:214 +0x66
github.com/formicidae-tracker/zeus.MissingDeviceAlarm.Reason(0xc0000b47b0, 0x6, 0xc000010030, 0xc000038500, 0x94d660)
/usr/local/src/zeus/alarm.go:61 +0x156
main.(*alarmMonitor).Monitor.func3(0xc00021c7c0, 0xc0001432c0, 0xc0000b04e0, 0x22)
/usr/local/src/zeus/zeus/alarm_monitor.go:91 +0x7c
created by main.(*alarmMonitor).Monitor
/usr/local/src/zeus/zeus/alarm_monitor.go:89 +0x57b

goroutine 11019 [runnable]:
main.(*alarmMonitor).Monitor.func2(0xc00021c7c0, 0x9d48c0, 0xc0000aa0c0)
/usr/local/src/zeus/zeus/alarm_monitor.go:66
created by main.(*alarmMonitor).Monitor
/usr/local/src/zeus/zeus/alarm_monitor.go:66 +0x294

goroutine 11022 [sleep]:
runtime.goparkunlock(...)
/usr/local/go/src/runtime/proc.go:307
time.Sleep(0x37e11d600)
/usr/local/go/src/runtime/time.go:105 +0x159
main.wakeupAfter(0xc000096420, 0xc000096480, 0xc0000b01e0, 0x22, 0x37e11d600)
/usr/local/src/zeus/zeus/alarm_monitor.go:30 +0x2f
created by main.(*alarmMonitor).Monitor
/usr/local/src/zeus/zeus/alarm_monitor.go:80 +0x3dc

goroutine 11021 [runnable]:
main.(*alarmMonitor).Monitor.func2(0xc00021c7c0, 0x9d48c0, 0xc0000aa0e0)
/usr/local/src/zeus/zeus/alarm_monitor.go:66
created by main.(*alarmMonitor).Monitor
/usr/local/src/zeus/zeus/alarm_monitor.go:66 +0x294

goroutine 11016 [sleep]:
runtime.goparkunlock(...)
/usr/local/go/src/runtime/proc.go:307
time.Sleep(0x37e11d600)
/usr/local/go/src/runtime/time.go:105 +0x159
main.wakeupAfter(0xc000096420, 0xc000096480, 0xc0000b0120, 0x21, 0x37e11d600)
/usr/local/src/zeus/zeus/alarm_monitor.go:30 +0x2f
created by main.(*alarmMonitor).Monitor
/usr/local/src/zeus/zeus/alarm_monitor.go:80 +0x3dc

goroutine 11020 [runnable]:
main.wakeupAfter(0xc000096420, 0xc000096480, 0xc000024580, 0x1f, 0x37e11d600)
/usr/local/src/zeus/zeus/alarm_monitor.go:29
created by main.(*alarmMonitor).Monitor
/usr/local/src/zeus/zeus/alarm_monitor.go:80 +0x3dc

goroutine 10732 [runnable]:
main.wakeupAfter(0xc000096420, 0xc000096480, 0xc0000246a0, 0x1f, 0x37e11d600)
/usr/local/src/zeus/zeus/alarm_monitor.go:41 +0xa5
created by main.(*alarmMonitor).Monitor
/usr/local/src/zeus/zeus/alarm_monitor.go:80 +0x3dc
```

**Comment by atuleu** [comment]
This issue is outdated with current version
